### ISSUE TITLE
Bitcoin blueprint publishes on wrong Mqtt topic

### ISSUE THREAD

**Issue by KoljaHenckel** [RDG88/Homeassistant_Blueprints#5]
Hi! 
Thanks for creating the cool blueprints!
I have an issue with your Bitcoin blueprint:
I renamed the topic of the Awtrix from aomething like awtrix_23423 to AWTRIX.
The Home Assistant MQTT device correctly shows this in the sensor 'Device topic'.
Unfortuantely, the blueprints writes to the "awtrix_23423" topic.
Maybe you can read the variable to set it?

Best
Cholera

**Comment by RDG88** [comment]
I will take a look, thanks for your feedback!

**Comment by RDG88** [comment]
The blueprint is updated to use multiple awtrix devices at once, this also should fix the problem when you change the topic to something else.. can you test? @KoljaHenckel
