### ISSUE TITLE
AWTRIX Klipper/Moonraker 3d print Sensor - Sensors not available

### ISSUE THREAD

**Issue by m0uh85** [RDG88/Homeassistant_Blueprints#6]
I have to printers integrated in HA with moonraker integration both of them have the sensors as entities but Im not able to choose them.

**Comment by RDG88** [comment]
Not sure why the filter is not working, i removed it, you should be able to select the sensor again.

Since i don't use moonraker anymore, i can't test.

**Comment by m0uh85** [comment]
I was able to select the Sensors but I'm not recieving any msg :(

**Comment by RDG88** [comment]
I still have my printer with klipper, il fire it up and see if i can fix it.. will take a bit

**Comment by m0uh85** [comment]
Thank! Take your time...

**Comment by m0uh85** [comment]
Any news? :(

**Comment by RDG88** [comment]
Sorry mate, im afraid i'm not able to test this intergration anymore.

**Comment by RDG88** [comment]
@m0uh85, are you able to join the AWTRIX Discord to do some troubleshooting, can be that we get it up and running together. https://discord.gg/rfjUDfUVUH, send me a msg: RobG
