### ISSUE TITLE
Awtrix Nightclock Mode

### ISSUE THREAD

**Issue by Goootz** [RDG88/Homeassistant_Blueprints#7]
Is it possible, that when Nightclock mode turns on and the device shows another application at this moment, that it automatically switches to the clock face? Didn't find the option and I don't want to switch it back to the clock every evening.
Thank you for your help!

**Comment by modem7** [comment]
Would definitely be useful here as well.

**Comment by RDG88** [comment]
I'm not totaly sure what you mean:

@Goootz @modem7 

Because there is an automatic switch line 317 to 322. I have it running at home also, and it automatically switches to the clock also when something else is displayed at that moment.. kind of the point of the blueprint :D

**Comment by RDG88** [comment]
Had contact with @modem7 via discord, seems that there was an error in the app name (in my blueprint).

Modified the code, can you please reimport the blueprint and test @Goootz ?

@modem7 confirmed that it works now.
