### ISSUE TITLE
Weekday Colour in Awtrix Night Clock

### ISSUE THREAD

**Issue by modem7** [RDG88/Homeassistant_Blueprints#8]
Heya, 

Would it be possible to introduce the ability to change the weekday colour via this blueprint? 

Cheers!

**Comment by RDG88** [comment]
https://github.com/RDG88/Homeassistant_Blueprints/commit/b71d86b93e898b68821891e7d8025b5dfcee186a

**Comment by RDG88** [comment]
Bugfix https://github.com/RDG88/Homeassistant_Blueprints/commit/165fb005b78984e184fd325403ea6fc33b94d781

**Comment by RDG88** [comment]
Closed

**Comment by modem7** [comment]
Apologies I didn't reply earlier! Shall test and if there are any issues, shall raise a ticket for it!

Thank you for doing this!

**Comment by modem7** [comment]
Have done a quick test and all seems to work as expected!
